import { store } from './data/store.js';
import { generateId } from './utils/ids.js';
import { currentRoute, startRouter } from './router.js';
import { navItems } from './components/sidebar.js';
import { showModal } from './components/modal.js';
import { showToast } from './components/toast.js';
import { renderDashboard } from './modules/dashboard.js';
import { renderVentas } from './modules/ventas.js';
import { renderFacturacion, cartTotal, productResults, customerResults } from './modules/facturacion.js';
import { renderProductos, productTable } from './modules/productos.js';
import { renderInventario, inventoryContent } from './modules/inventario.js';
import { renderTraslados, transferModal, transferTable } from './modules/traslados.js';
import { inventoryRows } from './utils/inventory.js';
import { renderClientes, customerTable } from './modules/clientes.js';
import { renderCreditos } from './modules/creditos.js';
import { renderCartera } from './modules/cartera.js';
import { renderLocales } from './modules/locales.js';
import { renderReportes } from './modules/reportes.js';
import { renderConfiguracion } from './modules/configuracion.js';
import { renderGastos } from './modules/gastos.js';
import { renderGasolina } from './modules/gasolina.js';
import { renderUsuarios } from './modules/usuarios.js';
import { renderAuditoria } from './modules/auditoria.js';
import { renderApartados } from './modules/apartados.js';
import { createApartado, decreaseSaleInventory, registerPayment } from './modules/finanzas.js';
import { formatCurrency as money } from './utils/currency.js';

const state = { cart: [], payment:'Efectivo', customerId:'CLI-00001', transport:0, transportDestination:'', transportNote:'' };
const transferDraft = [];
const $ = selector => document.querySelector(selector);
const views = { dashboard:()=>renderDashboard(store.collection), ventas:()=>renderVentas(store.collection), facturacion:()=>renderFacturacion(store.collection,state.cart,state.payment,state.customerId,state.transport,state.transportDestination,state.transportNote), productos:()=>renderProductos(store.collection), inventario:()=>renderInventario(store.collection), traslados:()=>renderTraslados(store.collection), clientes:()=>renderClientes(store.collection), creditos:()=>renderCreditos(store.collection), cartera:()=>renderCartera(store.collection), apartados:()=>renderApartados(store.collection), locales:()=>renderLocales(store.collection), gastos:()=>renderGastos(store.collection), gasolina:()=>renderGasolina(store.collection), auditoria:()=>renderAuditoria(store.collection), usuarios:()=>renderUsuarios(store.collection), reportes:renderReportes, configuracion:renderConfiguracion };
function renderNav(){ $('#main-nav').innerHTML=navItems.map(item=>`<a class="nav-item ${currentRoute()===item.id?'active':''}" href="#${item.id}"><span class="nav-icon">${item.icon}</span><span>${item.label}</span></a>`).join(''); $('#bottom-nav').innerHTML=navItems.slice(0,5).map(item=>`<a class="${currentRoute()===item.id?'active':''}" href="#${item.id}"><span>${item.icon}</span>${item.label}</a>`).join(''); }
function render(){ const route=currentRoute(); $('#section-title').textContent=navItems.find(item=>item.id===route)?.label||'Dashboard'; $('#app-content').innerHTML=views[route](); renderNav(); $('#sidebar').classList.remove('open'); }
function openModal(type){ const config={customer:['Nuevo cliente','Nombre completo'],product:['Nuevo producto','Nombre del producto'],credit:['Nuevo credito','Cliente'],payment:['Registrar pago','Valor del pago'],expense:['Nuevo gasto','Descripcion'],fuel:['Registrar gasolina','Vehiculo'],user:['Nuevo usuario','Nombre completo']}[type]; if(!config)return; showModal({title:config[0],label:config[1],onSubmit:value=>{if(!String(value).trim())return showToast('El campo es obligatorio.','error');if(type==='customer')store.add('customers',{id:generateId('CLI',store.collection.customers),name:value,document:'Pendiente',phone:'Pendiente',email:'demo@correo.test',purchases:0,credits:0,balance:0,status:'Activo'});if(type==='product')store.add('products',{id:generateId('PROD',store.collection.products),name:value,code:'NUEVO',reference:'NUEVO',category:'General',price:0,minimumPrice:0,stock:0,minimum:1,ideal:3,estado:'Activo',activo:true,storeId:'LOC-00001'});if(type==='credit')store.add('credits',{id:generateId('CR',store.collection.credits),customerId:state.customerId,saleId:null,total:0,originalAmount:0,initial:0,downPayment:0,paid:0,financedAmount:0,installmentsCount:1,installmentAmount:0,next:'Pendiente',date:'Ahora',status:'Al dia'});if(type==='payment')store.add('payments',{id:generateId('PAY',store.collection.payments),creditId:'CR-00001',installmentId:null,date:'Ahora',amount:Number(value)||0,method:'Efectivo'});if(type==='expense')store.add('expenses',{id:generateId('GAS',store.collection.expenses),date:'Ahora',storeId:'LOC-00001',category:'Otros',description:value,amount:0,paymentMethod:'Efectivo',createdBy:'USR-00001'});if(type==='fuel')store.add('fuelRecords',{id:generateId('FUE',store.collection.fuelRecords),date:'Ahora',storeId:'LOC-00001',vehicle:value,driver:'Pendiente',quantity:0,unit:'litros',amount:0,mileage:0,station:'Pendiente',createdBy:'USR-00001'});if(type==='user')store.add('users',{id:generateId('USR',store.collection.users),name:value,email:'demo@correo.test',role:'Vendedor',status:'Activo'});render();showToast('Registro guardado correctamente.');}}); }
function addProduct(productId){ const query=$('#billing-product')?.value.toLowerCase()||'';const product=store.collection.products.find(item=>item.id===productId)||store.collection.products.find(item=>item.stock>0&&`${item.name} ${item.code} ${item.reference}`.toLowerCase().includes(query));if(!product)return showToast('No hay productos suficientes.','error');const existing=state.cart.find(item=>item.id===product.id);if(existing)existing.quantity=Math.min(product.stock,existing.quantity+1);else state.cart.push({...product,priceLista:product.price,priceVenta:product.price,quantity:1});render();showToast('Producto agregado.');}
function finishSale(){if(!state.cart.length)return showToast('Agrega al menos un producto.','error');const sale={id:generateId('VEN',store.collection.sales),invoiceId:generateId('FAC',store.collection.sales),customerId:state.customerId,customer:store.collection.customers.find(item=>item.id===state.customerId)?.name||'Cliente contado',items:state.cart.map(item=>({productId:item.id,quantity:item.quantity,priceLista:item.priceLista,priceVenta:item.priceVenta})),transport:state.transport,transportDestination:state.transportDestination,transportNote:state.transportNote,paymentMethod:state.payment,total:cartTotal(state.cart,state.transport),date:'Ahora',status:'Completada'};store.add('sales',sale);if(state.payment==='CrÃ©dito interno FAMIMUEBLES'){const credit=store.add('credits',{id:generateId('CR',store.collection.credits),customerId:sale.customerId,saleId:sale.id,total:sale.total,originalAmount:sale.total,initial:0,downPayment:0,paid:0,financedAmount:sale.total,installmentsCount:6,installmentAmount:Math.ceil(sale.total/6),next:'Pendiente',date:'Ahora',status:'Al dia'});store.add('installments',{id:generateId('CUO',store.collection.installments),creditId:credit.id,number:1,dueDate:'Pendiente',amount:credit.installmentAmount,paidAmount:0,paymentDate:null,status:'Pendiente'});}state.cart=[];showToast('Venta creada correctamente.');render();}
function transferField(name){return document.querySelector(`.transfer-modal [data-transfer-${name}]`);}
function openTransfer(){transferDraft.length=0;$('#modal-root').innerHTML=transferModal(store.collection);$('.modal-close').addEventListener('click',()=>$('#modal-root').innerHTML='');updateTransferAvailability();}
function updateTransferAvailability(){const origin=transferField('origin')?.value,destination=transferField('destination')?.value,product=transferField('product')?.value;const a=inventoryRows(store.collection,origin).find(item=>item.product.id===product);const b=inventoryRows(store.collection,destination).find(item=>item.product.id===product);document.querySelector('.transfer-modal [data-transfer-origin-stock]')?.replaceChildren(String(a?.quantity||0));document.querySelector('.transfer-modal [data-transfer-destination-stock]')?.replaceChildren(String(b?.quantity||0));}
function addTransferItem(){const origin=transferField('origin').value,destination=transferField('destination').value,productId=transferField('product').value,quantity=Number(transferField('quantity').value),row=inventoryRows(store.collection,origin).find(item=>item.product.id===productId);if(origin===destination)return showToast('El origen y destino deben ser diferentes.','error');if(!row||quantity<=0||quantity>row.quantity)return showToast('La cantidad supera el stock disponible.','error');transferDraft.push({productId,quantity});$('#transfer-items').innerHTML=transferDraft.map(item=>`<p>${store.collection.products.find(product=>product.id===item.productId)?.name} Â· ${item.quantity} unidades</p>`).join('');showToast('Producto agregado al traslado.');}
function filterInventory(){const query=$('[data-filter="inventory"]')?.value.toLowerCase()||'',selected=$('[data-inventory-store]')?.value||'all';if($('#inventory-content'))$('#inventory-content').innerHTML=inventoryContent(store.collection,selected,query);}
function filterProducts(){const query=$('[data-filter="products"]')?.value.toLowerCase()||'',category=$('[data-product-category]')?.value||'Todos';const matches=store.collection.products.filter(item=>`${item.name} ${item.code} ${item.reference}`.toLowerCase().includes(query)&&(category==='Todos'||item.category===category));if($('#products-table'))$('#products-table').innerHTML=productTable(matches,store.collection.stores,50);if($('[data-product-count]'))$('[data-product-count]').textContent=`Mostrando ${Math.min(matches.length,50)} de ${matches.length} productos`;}
function filterTransfers(){const query=$('[data-filter="transfers"]')?.value.toLowerCase()||'',status=$('[data-transfer-status]')?.value||'Todos',origin=$('[data-transfer-origin]')?.value||'all',destination=$('[data-transfer-destination]')?.value||'all';const matches=store.collection.transfers.filter(item=>`${item.id} ${item.createdAt} ${item.status}`.toLowerCase().includes(query)&&(status==='Todos'||item.status===status)&&(origin==='all'||item.originStoreId===origin)&&(destination==='all'||item.destinationStoreId===destination));if($('#transfers-table'))$('#transfers-table').innerHTML=transferTable(store.collection,matches);}
document.addEventListener('click',event=>{const action=event.target.closest('[data-action]')?.dataset.action;if(action==='new-sale')location.hash='#facturacion';if(action==='new-customer')openModal('customer');if(action==='new-product')openModal('product');if(action==='new-credit')openModal('credit');if(action==='payment')openModal('payment');if(action==='new-expense')openModal('expense');if(action==='new-fuel')openModal('fuel');if(action==='new-user')openModal('user');if(action==='report')showToast('Generacion de reporte preparada para integracion futura.');if(action==='save-draft')showToast('Borrador guardado localmente.');if(action==='cancel-invoice'){state.cart=[];render();}if(action==='add-product')addProduct(event.target.closest('[data-product-id]')?.dataset.productId);if(action==='finish-sale')finishSale();if(event.target.dataset.remove){state.cart=state.cart.filter(item=>String(item.id)!==event.target.dataset.remove);render();}if(event.target.dataset.increase){const item=state.cart.find(entry=>entry.id===event.target.dataset.increase);if(item)item.quantity=Math.min(item.stock,item.quantity+1);render();}if(event.target.dataset.decrease){const item=state.cart.find(entry=>entry.id===event.target.dataset.decrease);if(item)item.quantity=Math.max(1,item.quantity-1);render();}if(event.target.dataset.productId&&!action)addProduct(event.target.dataset.productId);if(event.target.dataset.customerId){state.customerId=event.target.dataset.customerId;render();}if(event.target.dataset.payment){state.payment=event.target.dataset.payment;render();}if(action==='new-transfer')openTransfer();if(event.target.closest('[data-transfer-add]'))addTransferItem();});
document.addEventListener('input',event=>{if(event.target.dataset.price){const item=state.cart.find(entry=>entry.id===event.target.dataset.price);const product=store.collection.products.find(entry=>entry.id===item?.id);const value=Math.max(0,Number(event.target.value)||0);if(item&&product&&value>=product.minimumPrice){item.priceVenta=value;render();}else if(item&&product)showToast(`Precio minimo autorizado: ${money(product.minimumPrice)}.`,'error');}if(event.target.dataset.quantity){const item=state.cart.find(entry=>String(entry.id)===event.target.dataset.quantity);if(item)item.quantity=Math.min(item.stock,Math.max(1,Number(event.target.value)||1));render();}if(event.target.id==='billing-product')$('#product-results').innerHTML=productResults(store.collection.products.filter(item=>`${item.name} ${item.code} ${item.reference} ${item.category}`.toLowerCase().includes(event.target.value.toLowerCase())));if(event.target.id==='customer-search')$('#customer-results').innerHTML=customerResults(store.collection.customers.filter(item=>`${item.name} ${item.document} ${item.phone} ${item.id}`.toLowerCase().includes(event.target.value.toLowerCase())),state.customerId);if(event.target.matches('[data-filter="products"]'))filterProducts();if(event.target.matches('[data-filter="inventory"]'))filterInventory();if(event.target.matches('[data-filter="transfers"]'))filterTransfers();if(event.target.matches('[data-transfer-quantity]'))updateTransferAvailability();if(event.target.matches('[data-transport-value]')){state.transport=Math.max(0,Number(event.target.value)||0);render();}if(event.target.matches('[data-transport-destination]'))state.transportDestination=event.target.value;if(event.target.matches('[data-transport-note]'))state.transportNote=event.target.value;});
document.addEventListener('change',event=>{if(event.target.matches('[data-inventory-store]'))filterInventory();if(event.target.matches('[data-transfer-status],[data-transfer-origin],[data-transfer-destination],[data-transfer-date]'))filterTransfers();if(event.target.matches('[data-product-category]'))filterProducts();if(event.target.matches('[data-transfer-origin],[data-transfer-destination],[data-transfer-product]'))updateTransferAvailability();if(event.target.id==='dark-mode'){document.body.classList.toggle('dark',event.target.checked);localStorage.setItem('famimuebles-theme',event.target.checked?'dark':'light');}});
document.addEventListener('submit',event=>{if(!event.target.matches('.transfer-modal'))return;event.preventDefault();const origin=transferField('origin').value,destination=transferField('destination').value;if(origin===destination)return showToast('El origen y destino deben ser diferentes.','error');if(!transferDraft.length)return showToast('Agrega al menos un producto.','error');store.add('transfers',{id:generateId('TRS',store.collection.transfers),originStoreId:origin,destinationStoreId:destination,status:'Pendiente',createdAt:new Date().toISOString(),createdBy:'USR-00001',notes:'',items:[...transferDraft]});$('#modal-root').innerHTML='';showToast('Traslado creado correctamente.');render();});
$('#menu-toggle').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));$('#notification-toggle').dataset.action='notifications';document.addEventListener('click',event=>{if(event.target.dataset.payment)state.payment=event.target.dataset.payment;if(event.target.closest('[data-action="notifications"]'))showToast(store.collection.notifications.filter(item=>!item.read).map(item=>item.text).join(' · ')||'No hay notificaciones pendientes.');});if(localStorage.getItem('famimuebles-theme')==='dark')document.body.classList.add('dark');startRouter(render);
document.addEventListener('click',event=>{if(!event.target.closest('[data-action="finish-sale"]'))return;const sale=store.collection.sales.at(-1);if(!sale)return;if(state.payment==='Credito interno FAMIMUEBLES'&&!store.collection.credits.some(item=>item.saleId===sale.id)){const credit=store.add('credits',{id:generateId('CR',store.collection.credits),customerId:sale.customerId,saleId:sale.id,total:sale.total,originalAmount:sale.total,initial:0,downPayment:0,paid:0,financedAmount:sale.total,installmentsCount:6,installmentAmount:Math.ceil(sale.total/6),next:'Pendiente',date:'Ahora',status:'Al dia'});store.add('installments',{id:generateId('CUO',store.collection.installments),creditId:credit.id,number:1,dueDate:'Pendiente',amount:credit.installmentAmount,paidAmount:0,paymentDate:null,status:'Pendiente'});}sale.transport=state.transport;sale.transportDestination=state.transportDestination;sale.transportNote=state.transportNote;state.cart=[];store.add('auditLog',{id:generateId('AUD',store.collection.auditLog),date:'Ahora',userId:'USR-00001',action:'Crear venta',saleId:sale.id,storeId:'LOC-00001'});});
document.addEventListener('click',event=>{if(!event.target.closest('[data-action="finish-sale"]'))return;const sale=store.collection.sales.at(-1);if(!sale)return;sale.items.filter(item=>(item.priceVenta??item.price)!==(item.priceLista??item.price)).forEach(item=>{const product=store.collection.products.find(entry=>entry.id===item.productId);store.add('auditLog',{id:generateId('AUD',store.collection.auditLog),date:'Ahora',userId:'USR-00001',action:'Precio negociado',saleId:sale.id,productId:item.productId,listPrice:item.priceLista,salePrice:item.priceVenta,difference:item.priceLista-item.priceVenta,storeId:'LOC-00001'});});if(!String(state.payment).toLowerCase().includes('intern')||store.collection.credits.some(item=>item.saleId===sale.id))return;const credit=store.add('credits',{id:generateId('CR',store.collection.credits),customerId:sale.customerId,saleId:sale.id,total:sale.total,originalAmount:sale.total,initial:0,downPayment:0,paid:0,financedAmount:sale.total,installmentsCount:6,installmentAmount:Math.ceil(sale.total/6),next:'Pendiente',date:'Ahora',status:'Al dia'});store.add('installments',{id:generateId('CUO',store.collection.installments),creditId:credit.id,number:1,dueDate:'Pendiente',amount:credit.installmentAmount,paidAmount:0,paymentDate:null,status:'Pendiente'});});

function financeModal() {
	const credits = store.collection.credits.filter(item => item.status !== 'Saldado');
	const apartados = store.collection.apartados.filter(item => item.status !== 'Liquidado');
	$('#modal-root').innerHTML = `<div class="modal-backdrop"><form class="modal" id="finance-payment-form"><button type="button" class="modal-close">×</button><p class="eyebrow">FAMIMUEBLES ERP</p><h2>Registrar abono</h2><label class="input-label">Cuenta</label><select class="field" required data-payment-target>${credits.map(item => `<option value="credit:${item.id}">Credito ${item.id} · ${item.customer}</option>`).concat(apartados.map(item => `<option value="apartado:${item.id}">Apartado ${item.id} · ${item.customer}</option>`)).join('')}</select><label class="input-label">Valor del abono</label><input class="field" type="number" min="1" required autofocus data-payment-amount><label class="input-label">Medio de pago</label><select class="field" data-payment-method><option>Efectivo</option><option>Transferencia</option><option>Tarjeta</option></select><button class="primary wide">Guardar abono</button></form></div>`;
	$('.modal-close').addEventListener('click', () => $('#modal-root').innerHTML = '');
	$('#finance-payment-form').addEventListener('submit', event => {
		event.preventDefault();
		const [kind, id] = $('[data-payment-target]').value.split(':');
		try { registerPayment(store.collection, { kind, id }, $('[data-payment-amount]').value, $('[data-payment-method]').value); store.save(); $('#modal-root').innerHTML = ''; showToast(kind === 'apartado' ? 'Abono registrado. El apartado se convierte en venta al liquidarse.' : 'Abono registrado.'); render(); } catch (error) { showToast(error.message, 'error'); }
	});
}

document.addEventListener('click', event => {
	const action = event.target.closest('[data-action]')?.dataset.action;
	if (action === 'payment') { event.stopImmediatePropagation(); financeModal(); }
	if (action !== 'finish-sale') return;
	event.stopImmediatePropagation();
	if (!state.cart.length) return showToast('Agrega al menos un producto.', 'error');
	const sale = { id:generateId('VEN',store.collection.sales), invoiceId:generateId('FAC',store.collection.sales), customerId:state.customerId, customer:store.collection.customers.find(item=>item.id===state.customerId)?.name||'Cliente contado', items:state.cart.map(item=>({productId:item.id,quantity:item.quantity,priceLista:item.priceLista,priceVenta:item.priceVenta})), transport:state.transport, transportDestination:state.transportDestination, transportNote:state.transportNote, paymentMethod:state.payment, total:cartTotal(state.cart,state.transport), date:'Ahora', status:'Completada', storeId:'LOC-00001' };
	try {
		store.add('sales', sale);
		if (state.payment === 'Apartado') { sale.status = 'Apartado'; createApartado(store.collection, sale, Number($('[data-apartado-initial]')?.value || 0), 'Efectivo'); }
		else { decreaseSaleInventory(store.collection, sale); if (state.payment.toLowerCase().includes('intern')) { const credit = store.add('credits',{id:generateId('CR',store.collection.credits),customerId:sale.customerId,saleId:sale.id,customer:sale.customer,total:sale.total,originalAmount:sale.total,initial:0,downPayment:0,paid:0,financedAmount:sale.total,installmentsCount:6,installmentAmount:Math.ceil(sale.total/6),next:'Pendiente',date:'Ahora',status:'Al dia'}); store.add('installments',{id:generateId('CUO',store.collection.installments),creditId:credit.id,number:1,dueDate:'Pendiente',amount:credit.installmentAmount,paidAmount:0,paymentDate:null,status:'Pendiente'}); } }
		store.save(); state.cart=[]; showToast(state.payment === 'Apartado' ? 'Apartado creado. La mercancía queda pendiente de entrega.' : 'Venta creada y stock actualizado.'); render();
	} catch (error) { store.collection.sales = store.collection.sales.filter(item => item.id !== sale.id); showToast(error.message, 'error'); }
}, true);
