import { money, table, badge } from '../components/tables.js';
import { inventoryRows } from '../utils/inventory.js';

export function productDetail(state, productId) {
  const product = state.products.find(item => item.id === productId);
  if (!product) return '<p class="empty-state">Producto no encontrado.</p>';
  const rows = inventoryRows(state).filter(row => row.product.id === productId);
  const total = rows.reduce((sum, row) => sum + Number(row.quantity || 0), 0);
  const movements = state.inventoryMovements.filter(item => item.productId === productId).slice(-20).reverse();
  return `<div class="modal-backdrop"><section class="modal product-detail-modal"><button type="button" class="modal-close">×</button><p class="eyebrow">FICHA DEL PRODUCTO</p><div class="product-detail-head"><div class="product-art detail-art">${product.name[0]}</div><div><h2>${product.name}</h2><p>${product.code} · ${product.reference || '-'}</p></div></div><div class="detail-grid"><div><span>Codigo de barras</span><strong>${product.barcode || '-'}</strong></div><div><span>Categoria</span><strong>${product.categoryName || product.category || '-'}</strong></div><div><span>Subcategoria</span><strong>${product.subcategoryName || product.subcategory || '-'}</strong></div><div><span>Marca</span><strong>${product.brand || '-'}</strong></div><div><span>Proveedor</span><strong>${product.supplierName || '-'}</strong></div><div><span>Estado</span><strong>${badge(product.active === false ? 'Inactivo' : 'Activo')}</strong></div><div><span>Costo</span><strong>${money(product.cost || 0)}</strong></div><div><span>Precio venta</span><strong>${money(product.salePrice ?? product.price ?? 0)}</strong></div><div><span>Precio especial</span><strong>${money(product.specialPrice || 0)}</strong></div><div><span>IVA</span><strong>${product.iva || 0}%</strong></div><div><span>Stock minimo</span><strong>${product.minStock ?? product.minimum ?? 0}</strong></div><div><span>Stock maximo</span><strong>${product.maxStock ?? product.maximum ?? 0}</strong></div></div><p>${product.description || 'Sin descripcion.'}</p><h3>Inventario por local · Total ${total}</h3>${table(['Local','Stock','Minimo','Maximo','Estado','Acciones'],rows.map(row=>`<tr><td>${row.store.name}</td><td><strong>${row.quantity}</strong></td><td>${row.minimumStock}</td><td>${row.maximum ?? product.maximum ?? '-'}</td><td>${badge(row.status)}</td><td><button class="table-action" data-action="adjust-inventory" data-product-id="${product.id}" data-store-id="${row.store.id}">Ajustar</button></td></tr>`))}<h3>Historial del producto</h3>${table(['Fecha','Tipo','Local','Cantidad','Documento','Observacion'],movements.map(item=>`<tr><td>${item.createdAt}</td><td>${item.type}</td><td>${state.stores.find(store=>store.id===item.storeId)?.name || item.storeId}</td><td>${item.quantity}</td><td>${item.referenceId || '-'}</td><td>${item.note || '-'}</td></tr>`))}</section></div>`;
}
